name: Publish image

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPOSITORY: akimon658/ogjson

    steps:
      - uses: actions/checkout@v2

      - uses: olegtarasov/get-tag@b760c7889c8696fd68c69eb68f7260b9c3a5f1f6
        id: tagName
        with:
          tagRegex: 'v(.*)'

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: akimon658
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.REPOSITORY }}:${{ steps.tagName.outputs.tag }}
            ${{ env.REPOSITORY }}:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ env.REPOSITORY }}:${{ steps.tagName.outputs.tag }}
            ghcr.io/${{ env.REPOSITORY }}:latest

      - name: Login to GitLab Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: akimon658
          password: ${{ secrets.GITLAB_TOKEN }}

      - name: Push to GitLab Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            registry.gitlab.com/${{ env.REPOSITORY }}:${{ steps.tagName.outputs.tag }}
            registry.gitlab.com/${{ env.REPOSITORY }}:latest
